//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBedManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestBedManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons/bullet_green.png.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string DefaultHostname {
            get {
                return ResourceManager.GetString("DefaultHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled List.
        /// </summary>
        internal static string DefaultTestbedName {
            get {
                return ResourceManager.GetString("DefaultTestbedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons/bullet_red.png.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerInfo.
        /// </summary>
        internal static string TableName_Computers {
            get {
                return ResourceManager.GetString("TableName_Computers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListRelations.
        /// </summary>
        internal static string TableName_TestbedRelations {
            get {
                return ResourceManager.GetString("TableName_TestbedRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        internal static string TableName_Testbeds {
            get {
                return ResourceManager.GetString("TableName_Testbeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons/bullet_black.png.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons/check.png.
        /// </summary>
        internal static string WmiConnected {
            get {
                return ResourceManager.GetString("WmiConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not contact the Windows Management Instrumentation (WMI) service on the remote computer.
        ///
        ///Possible solutions:
        ///	- Verify that the username and password are correct.
        ///	- Ensure that the supplied user is a member of the Administrators group.
        ///	- Make sure that WMI Control is allowed on the remote machine.
        ///	- The minimum OS required is Windows 2000; only Windows is supported..
        /// </summary>
        internal static string WmiErrorMsg {
            get {
                return ResourceManager.GetString("WmiErrorMsg", resourceCulture);
            }
        }
    }
}
